{% set name = "bw2speedups" %}
{% set version = "2.3" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': '4717aabbc4d3aba28f3f7368ad74807053c6db65842d0d5a772d42785ae9e7cb'

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - numpy
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - bw2speedups

about:
  home: https://bitbucket.org/cmutel/brightway2-speedups
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Cython functions to speed up Brightway2 LCA calculations
  description: 'A series of function written in Cython that speed up critical functions to improve the overall performance of the Brightway2 life cycle assessment framework.'
  doc_url: https://bitbucket.org/cmutel/brightway2-speedups
  dev_url: https://bitbucket.org/cmutel/brightway2-speedups

extra:
  recipe-maintainers:
    - cardosan
    - cmutel
