appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: czSv2BzYftDtmUFucUwjwUI471mEUr9B71D7EA9FphNbntoCUCpNPILB5om6CnYGspoYhWJrgt3hgN2g9JBHTIbQX2Zpp6lxOAYntxums1U1wH/piKxr77RB/sdv1I487GMXfLdcZEQtL/Y15/+mKNKfdki9jnTwFdZDDv2LyHjFLg1Aly0RMlx09oKS0QofbadAzkeaGfBhBk3pdZNF5LzufJcNwbTrQDG25dsnV1yobqqExVxWvUXhEvs2fFBEdWDUAFt4ofqa+Kat/xBYFfndGAvvN1pZ9VI9ofpwX7gnlUwUWsr/4l9Fu+eeLhlXSW32l97dNOln1whh7oTHBCbQJ6uMbk5mQbIf/xAu83E7pyY9GTCGStWoGoHsDzfqmOs9uCfM/LCg79bjHukcVMCIkfVOmdERYsohw/oAiaJG3iRJNRfV85FsbXUCzN0CdtZsnVkqyy9CDchhzraPagjavU3a6etnqSjeT8xJfOilyYjXyXCd9c1IC8rd0HarVtlKEPFTCth7FAaKqmZfugbevlHMrUyPIOAZKqsJFV65V7IYHnbremhPFN42RH6UeRi3E7K8UgayfJbMCu5wS+2KRW4HvYJiXum0KDzJetSXHIlc8bAYC0GRipYzPz3insVeFVOlSqWocrVXSg7jMbTEvonEkkOUozH7VIX8UsU=}
provider:
  win: azure
conda_forge_output_validation: true
